// User Actions
export const SET_USER = "SET_USER";
export const TOGGLE_AUTHENTICATING = "TOGGLE_AUTHENTICATING";
export const LOGOUT_USER = "LOGOUT_USER";
export const EXPIRE_REFRESH_TOKEN = "EXPIRE_USER_TOKEN";
export const UPDATE_ACCESS_TOKEN = "UPDATE_USER_TOKEN";

// Data actions
export const FETCH_USER_PROFILE_DATA = "FETCH_USER_PROFILE_DATA";
export const TOGGLE_FETCHING = "TOGGLE_FETCHING";
export const FETCH_ALL_OPEN_JOBS = "FETCH_ALL_OPEN_JOBS";
export const FETCH_JOB_DETAILS = "FETCH_JOB_DETAILS";
export const FETCH_CLIENT_ALL_JOBS = "FETCH_CLIENT_ALL_JOBS";
export const FETCH_ALL_JOB_APPLICATIONS = "FETCH_ALL_JOB_APPLICATIONS";
export const FETCH_CLIENT_REVIEW = "FETCH_CLIENT_REVIEW";
export const FETCH_JOB_DETAILS_HISTORY = "FETCH_JOB_DETAILS_HISTORY";
export const SET_CHAT_ROOM = "SET_CHAT_ROOM";
export const FETCH_CHAT_ROOM_MESSAGES = "FETCH_CHAT_ROOM_MESSAGES";
export const FETCH_ALL_CHAT_ROOMS = "FETCH_ALL_CHAT_ROOMS";
